global:
  checkNewVersion: false
  sendAnonymousUsage: false

#api:
#  dashboard: true

#ping: {}

entryPoints:
  http:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: https
          scheme: https
  https:
    address: ":443"
    http:
      tls:
        options: default

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    watch: true
    exposedByDefault: false
    # change to match the network name created by docker-compose
    network: ns-traefik_rp
  file:
    filename: /etc/traefik/config.yml

# frontend certificates
certificatesResolvers:
  acmeTLS:
    acme:
      # change address
      email: xxxxxxxxxxx
      storage: /etc/traefik/acme/acmeTLS.json
      tlsChallenge: {}

log: {}
